spring:
  datasource:
             url: jdbc:mysql://127.0.0.1:3306/appdev
             username: root
             password: root2018
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: me.maiz.trainning.demo.helloboot.dal.model

