package me.maiz.trainning.framework.mybatis.dal.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RoadExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public RoadExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoadidIsNull() {
            addCriterion("ROADID is null");
            return (Criteria) this;
        }

        public Criteria andRoadidIsNotNull() {
            addCriterion("ROADID is not null");
            return (Criteria) this;
        }

        public Criteria andRoadidEqualTo(BigDecimal value) {
            addCriterion("ROADID =", value, "roadid");
            return (Criteria) this;
        }

        public Criteria andRoadidNotEqualTo(BigDecimal value) {
            addCriterion("ROADID <>", value, "roadid");
            return (Criteria) this;
        }

        public Criteria andRoadidGreaterThan(BigDecimal value) {
            addCriterion("ROADID >", value, "roadid");
            return (Criteria) this;
        }

        public Criteria andRoadidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ROADID >=", value, "roadid");
            return (Criteria) this;
        }

        public Criteria andRoadidLessThan(BigDecimal value) {
            addCriterion("ROADID <", value, "roadid");
            return (Criteria) this;
        }

        public Criteria andRoadidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ROADID <=", value, "roadid");
            return (Criteria) this;
        }

        public Criteria andRoadidIn(List<BigDecimal> values) {
            addCriterion("ROADID in", values, "roadid");
            return (Criteria) this;
        }

        public Criteria andRoadidNotIn(List<BigDecimal> values) {
            addCriterion("ROADID not in", values, "roadid");
            return (Criteria) this;
        }

        public Criteria andRoadidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ROADID between", value1, value2, "roadid");
            return (Criteria) this;
        }

        public Criteria andRoadidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ROADID not between", value1, value2, "roadid");
            return (Criteria) this;
        }

        public Criteria andRoadNameIsNull() {
            addCriterion("ROAD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRoadNameIsNotNull() {
            addCriterion("ROAD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRoadNameEqualTo(String value) {
            addCriterion("ROAD_NAME =", value, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameNotEqualTo(String value) {
            addCriterion("ROAD_NAME <>", value, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameGreaterThan(String value) {
            addCriterion("ROAD_NAME >", value, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameGreaterThanOrEqualTo(String value) {
            addCriterion("ROAD_NAME >=", value, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameLessThan(String value) {
            addCriterion("ROAD_NAME <", value, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameLessThanOrEqualTo(String value) {
            addCriterion("ROAD_NAME <=", value, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameLike(String value) {
            addCriterion("ROAD_NAME like", value, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameNotLike(String value) {
            addCriterion("ROAD_NAME not like", value, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameIn(List<String> values) {
            addCriterion("ROAD_NAME in", values, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameNotIn(List<String> values) {
            addCriterion("ROAD_NAME not in", values, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameBetween(String value1, String value2) {
            addCriterion("ROAD_NAME between", value1, value2, "roadName");
            return (Criteria) this;
        }

        public Criteria andRoadNameNotBetween(String value1, String value2) {
            addCriterion("ROAD_NAME not between", value1, value2, "roadName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TJS_ROAD
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 22 14:26:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}