package me.maiz.trainning.framework.mybatis.dal.entity;

import java.math.BigDecimal;

public class Road {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TJS_ROAD.ROADID
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    private BigDecimal roadid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TJS_ROAD.ROAD_NAME
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    private String roadName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TJS_ROAD.ROADID
     *
     * @return the value of TJS_ROAD.ROADID
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public BigDecimal getRoadid() {
        return roadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TJS_ROAD.ROADID
     *
     * @param roadid the value for TJS_ROAD.ROADID
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public void setRoadid(BigDecimal roadid) {
        this.roadid = roadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TJS_ROAD.ROAD_NAME
     *
     * @return the value of TJS_ROAD.ROAD_NAME
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public String getRoadName() {
        return roadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TJS_ROAD.ROAD_NAME
     *
     * @param roadName the value for TJS_ROAD.ROAD_NAME
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    public void setRoadName(String roadName) {
        this.roadName = roadName == null ? null : roadName.trim();
    }
}