package me.maiz.trainning.framework.mybatis.dal.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TJS_USER.USER_ID
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TJS_USER.USERNAME
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TJS_USER.PASSWORD
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TJS_USER.AGE
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    private Long age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TJS_USER.BIRTHDAY
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    private Date birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TJS_USER.USER_ID
     *
     * @return the value of TJS_USER.USER_ID
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TJS_USER.USER_ID
     *
     * @param userId the value for TJS_USER.USER_ID
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TJS_USER.USERNAME
     *
     * @return the value of TJS_USER.USERNAME
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TJS_USER.USERNAME
     *
     * @param username the value for TJS_USER.USERNAME
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TJS_USER.PASSWORD
     *
     * @return the value of TJS_USER.PASSWORD
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TJS_USER.PASSWORD
     *
     * @param password the value for TJS_USER.PASSWORD
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TJS_USER.AGE
     *
     * @return the value of TJS_USER.AGE
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    public Long getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TJS_USER.AGE
     *
     * @param age the value for TJS_USER.AGE
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    public void setAge(Long age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TJS_USER.BIRTHDAY
     *
     * @return the value of TJS_USER.BIRTHDAY
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TJS_USER.BIRTHDAY
     *
     * @param birthday the value for TJS_USER.BIRTHDAY
     *
     * @mbggenerated Tue Mar 20 15:24:21 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
}