spring:
  application:
    name: langchain4j-demo
langchain4j:
  open-ai:
    chat-model:
      api-key: ${DASHSCOPE_API_KEY}                            # 阿里百炼 API Key
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1  # 百炼 OpenAI 兼容模式
      model-name: qwen-plus                                   # 通义千问对话模型
      temperature: 0.7
      log-requests: true
      log-responses: true
    embedding-model:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: text-embedding-v3                           # 通义千问 Embedding 模型
      max-batch-size: 10
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: qwen-plus
      temperature: 0.7
      log-requests: true
      log-responses: true
