package me.maiz.trainning.framework.ssm.dal.mapper;

import java.math.BigDecimal;
import java.util.List;
import me.maiz.trainning.framework.ssm.dal.model.Road;
import me.maiz.trainning.framework.ssm.dal.model.RoadExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RoadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    long countByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int deleteByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal roadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int insert(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int insertSelective(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    List<Road> selectByExampleWithRowbounds(RoadExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    List<Road> selectByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    Road selectByPrimaryKey(BigDecimal roadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") Road record, @Param("example") RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int updateByExample(@Param("record") Road record, @Param("example") RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int updateByPrimaryKeySelective(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int updateByPrimaryKey(Road record);
}