package me.maiz.trainning.framework.mybatis.dal.mapper;

import java.math.BigDecimal;
import java.util.List;
import me.maiz.trainning.framework.mybatis.dal.entity.Road;
import me.maiz.trainning.framework.mybatis.dal.entity.RoadExample;
import org.apache.ibatis.annotations.Param;

public interface RoadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    int countByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    int deleteByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal roadid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    int insert(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    int insertSelective(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    List<Road> selectByExample(RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    Road selectByPrimaryKey(BigDecimal roadid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") Road record, @Param("example") RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    int updateByExample(@Param("record") Road record, @Param("example") RoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    int updateByPrimaryKeySelective(Road record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbggenerated Thu Mar 22 14:26:10 CST 2018
     */
    int updateByPrimaryKey(Road record);
}