
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rocket
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  type-aliases-package: me.maiz.project.eduk15boss.model
  mapper-locations: classpath:mappers/**/*.xml
logging:
  level:
    org:
      apache:
        shiro: debug