package me.maiz.trainning.framework.ssm.dal.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Road implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TJS_ROAD.ROAD_ID
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    private BigDecimal roadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TJS_ROAD.ROAD_NAME
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    private String roadName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TJS_ROAD.ROAD_ID
     *
     * @return the value of TJS_ROAD.ROAD_ID
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    public BigDecimal getRoadId() {
        return roadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TJS_ROAD.ROAD_ID
     *
     * @param roadId the value for TJS_ROAD.ROAD_ID
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    public void setRoadId(BigDecimal roadId) {
        this.roadId = roadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TJS_ROAD.ROAD_NAME
     *
     * @return the value of TJS_ROAD.ROAD_NAME
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    public String getRoadName() {
        return roadName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TJS_ROAD.ROAD_NAME
     *
     * @param roadName the value for TJS_ROAD.ROAD_NAME
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    public void setRoadName(String roadName) {
        this.roadName = roadName == null ? null : roadName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TJS_ROAD
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roadId=").append(roadId);
        sb.append(", roadName=").append(roadName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}