package me.maiz.project.eduk15boss.dao;

import java.util.List;
import me.maiz.project.eduk15boss.model.OperatorRole;
import me.maiz.project.eduk15boss.model.OperatorRoleExample;
import org.apache.ibatis.annotations.Param;

public interface OperatorRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    long countByExample(OperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int deleteByExample(OperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int deleteByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int insert(OperatorRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int insertSelective(OperatorRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    List<OperatorRole> selectByExample(OperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    OperatorRole selectByPrimaryKey(Integer userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") OperatorRole record, @Param("example") OperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByExample(@Param("record") OperatorRole record, @Param("example") OperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByPrimaryKeySelective(OperatorRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByPrimaryKey(OperatorRole record);
}