package me.maiz.project.eduk15boss.dao;

import java.util.List;
import me.maiz.project.eduk15boss.model.Operator;
import me.maiz.project.eduk15boss.model.OperatorExample;
import org.apache.ibatis.annotations.Param;

public interface OperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    long countByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int deleteByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int deleteByPrimaryKey(Integer operatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int insert(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int insertSelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    List<Operator> selectByExample(OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    Operator selectByPrimaryKey(Integer operatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") Operator record, @Param("example") OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByExample(@Param("record") Operator record, @Param("example") OperatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByPrimaryKeySelective(Operator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByPrimaryKey(Operator record);
}