package me.maiz.project.eduk15boss.dao;

import java.util.List;
import me.maiz.project.eduk15boss.model.Permisson;
import me.maiz.project.eduk15boss.model.PermissonExample;
import org.apache.ibatis.annotations.Param;

public interface PermissonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    long countByExample(PermissonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int deleteByExample(PermissonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int deleteByPrimaryKey(Integer permId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int insert(Permisson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int insertSelective(Permisson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    List<Permisson> selectByExample(PermissonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    Permisson selectByPrimaryKey(Integer permId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") Permisson record, @Param("example") PermissonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByExample(@Param("record") Permisson record, @Param("example") PermissonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByPrimaryKeySelective(Permisson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByPrimaryKey(Permisson record);
}