package me.maiz.project.eduk15boss.dao;

import java.util.List;
import me.maiz.project.eduk15boss.model.Role;
import me.maiz.project.eduk15boss.model.RoleExample;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    Role selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByPrimaryKey(Role record);
}