package me.maiz.project.eduk15boss.dao;

import java.util.List;
import me.maiz.project.eduk15boss.model.Teacher;
import me.maiz.project.eduk15boss.model.TeacherExample;
import org.apache.ibatis.annotations.Param;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    long countByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int deleteByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int deleteByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    List<Teacher> selectByExample(TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    Teacher selectByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") Teacher record, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByExample(@Param("record") Teacher record, @Param("example") TeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    int updateByPrimaryKey(Teacher record);
}