server:
  port: 8083

spring:
  application:
    name: a2a-client-service
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-turbo

alibaba:
  a2a:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        enabled: true
        namespace: public
        group: DEFAULT_GROUP

logging:
  level:
    com.alibaba.cloud.ai: DEBUG