package me.maiz.project.eduk15boss.model;

import java.io.Serializable;

public class OperatorRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator_role.user_role_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator_role.user_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator_role.role_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator_role.user_role_id
     *
     * @return the value of boss_operator_role.user_role_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator_role.user_role_id
     *
     * @param userRoleId the value for boss_operator_role.user_role_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setUserRoleId(Integer userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator_role.user_id
     *
     * @return the value of boss_operator_role.user_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator_role.user_id
     *
     * @param userId the value for boss_operator_role.user_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator_role.role_id
     *
     * @return the value of boss_operator_role.role_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator_role.role_id
     *
     * @param roleId the value for boss_operator_role.role_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator_role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userRoleId=").append(userRoleId);
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}