package me.maiz.project.eduk15boss.model;

import java.io.Serializable;
import java.util.Date;

public class Operator implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator.operator_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator.operator_name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator.password
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator.mobile
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator.email
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator.name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator.raw_add_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Date rawAddTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_operator.raw_update_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Date rawUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator.operator_id
     *
     * @return the value of boss_operator.operator_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator.operator_id
     *
     * @param operatorId the value for boss_operator.operator_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator.operator_name
     *
     * @return the value of boss_operator.operator_name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator.operator_name
     *
     * @param operatorName the value for boss_operator.operator_name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator.password
     *
     * @return the value of boss_operator.password
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator.password
     *
     * @param password the value for boss_operator.password
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator.mobile
     *
     * @return the value of boss_operator.mobile
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator.mobile
     *
     * @param mobile the value for boss_operator.mobile
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator.email
     *
     * @return the value of boss_operator.email
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator.email
     *
     * @param email the value for boss_operator.email
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator.name
     *
     * @return the value of boss_operator.name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator.name
     *
     * @param name the value for boss_operator.name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator.raw_add_time
     *
     * @return the value of boss_operator.raw_add_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Date getRawAddTime() {
        return rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator.raw_add_time
     *
     * @param rawAddTime the value for boss_operator.raw_add_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRawAddTime(Date rawAddTime) {
        this.rawAddTime = rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_operator.raw_update_time
     *
     * @return the value of boss_operator.raw_update_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Date getRawUpdateTime() {
        return rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_operator.raw_update_time
     *
     * @param rawUpdateTime the value for boss_operator.raw_update_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRawUpdateTime(Date rawUpdateTime) {
        this.rawUpdateTime = rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_operator
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", operatorId=").append(operatorId);
        sb.append(", operatorName=").append(operatorName);
        sb.append(", password=").append(password);
        sb.append(", mobile=").append(mobile);
        sb.append(", email=").append(email);
        sb.append(", name=").append(name);
        sb.append(", rawAddTime=").append(rawAddTime);
        sb.append(", rawUpdateTime=").append(rawUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}