package me.maiz.project.eduk15boss.model;

import java.io.Serializable;

public class Permisson implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_permission.perm_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer permId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_permission.perm_name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String permName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_permission.perm_value
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String permValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_permission.perm_attachment
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String permAttachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_permission.perm_id
     *
     * @return the value of boss_permission.perm_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getPermId() {
        return permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_permission.perm_id
     *
     * @param permId the value for boss_permission.perm_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setPermId(Integer permId) {
        this.permId = permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_permission.perm_name
     *
     * @return the value of boss_permission.perm_name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getPermName() {
        return permName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_permission.perm_name
     *
     * @param permName the value for boss_permission.perm_name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setPermName(String permName) {
        this.permName = permName == null ? null : permName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_permission.perm_value
     *
     * @return the value of boss_permission.perm_value
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getPermValue() {
        return permValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_permission.perm_value
     *
     * @param permValue the value for boss_permission.perm_value
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setPermValue(String permValue) {
        this.permValue = permValue == null ? null : permValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_permission.perm_attachment
     *
     * @return the value of boss_permission.perm_attachment
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getPermAttachment() {
        return permAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_permission.perm_attachment
     *
     * @param permAttachment the value for boss_permission.perm_attachment
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setPermAttachment(String permAttachment) {
        this.permAttachment = permAttachment == null ? null : permAttachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", permId=").append(permId);
        sb.append(", permName=").append(permName);
        sb.append(", permValue=").append(permValue);
        sb.append(", permAttachment=").append(permAttachment);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}