package me.maiz.project.eduk15boss.model;

import java.util.ArrayList;
import java.util.List;

public class PermissonExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public PermissonExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPermIdIsNull() {
            addCriterion("perm_id is null");
            return (Criteria) this;
        }

        public Criteria andPermIdIsNotNull() {
            addCriterion("perm_id is not null");
            return (Criteria) this;
        }

        public Criteria andPermIdEqualTo(Integer value) {
            addCriterion("perm_id =", value, "permId");
            return (Criteria) this;
        }

        public Criteria andPermIdNotEqualTo(Integer value) {
            addCriterion("perm_id <>", value, "permId");
            return (Criteria) this;
        }

        public Criteria andPermIdGreaterThan(Integer value) {
            addCriterion("perm_id >", value, "permId");
            return (Criteria) this;
        }

        public Criteria andPermIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("perm_id >=", value, "permId");
            return (Criteria) this;
        }

        public Criteria andPermIdLessThan(Integer value) {
            addCriterion("perm_id <", value, "permId");
            return (Criteria) this;
        }

        public Criteria andPermIdLessThanOrEqualTo(Integer value) {
            addCriterion("perm_id <=", value, "permId");
            return (Criteria) this;
        }

        public Criteria andPermIdIn(List<Integer> values) {
            addCriterion("perm_id in", values, "permId");
            return (Criteria) this;
        }

        public Criteria andPermIdNotIn(List<Integer> values) {
            addCriterion("perm_id not in", values, "permId");
            return (Criteria) this;
        }

        public Criteria andPermIdBetween(Integer value1, Integer value2) {
            addCriterion("perm_id between", value1, value2, "permId");
            return (Criteria) this;
        }

        public Criteria andPermIdNotBetween(Integer value1, Integer value2) {
            addCriterion("perm_id not between", value1, value2, "permId");
            return (Criteria) this;
        }

        public Criteria andPermNameIsNull() {
            addCriterion("perm_name is null");
            return (Criteria) this;
        }

        public Criteria andPermNameIsNotNull() {
            addCriterion("perm_name is not null");
            return (Criteria) this;
        }

        public Criteria andPermNameEqualTo(String value) {
            addCriterion("perm_name =", value, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameNotEqualTo(String value) {
            addCriterion("perm_name <>", value, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameGreaterThan(String value) {
            addCriterion("perm_name >", value, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameGreaterThanOrEqualTo(String value) {
            addCriterion("perm_name >=", value, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameLessThan(String value) {
            addCriterion("perm_name <", value, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameLessThanOrEqualTo(String value) {
            addCriterion("perm_name <=", value, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameLike(String value) {
            addCriterion("perm_name like", value, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameNotLike(String value) {
            addCriterion("perm_name not like", value, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameIn(List<String> values) {
            addCriterion("perm_name in", values, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameNotIn(List<String> values) {
            addCriterion("perm_name not in", values, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameBetween(String value1, String value2) {
            addCriterion("perm_name between", value1, value2, "permName");
            return (Criteria) this;
        }

        public Criteria andPermNameNotBetween(String value1, String value2) {
            addCriterion("perm_name not between", value1, value2, "permName");
            return (Criteria) this;
        }

        public Criteria andPermValueIsNull() {
            addCriterion("perm_value is null");
            return (Criteria) this;
        }

        public Criteria andPermValueIsNotNull() {
            addCriterion("perm_value is not null");
            return (Criteria) this;
        }

        public Criteria andPermValueEqualTo(String value) {
            addCriterion("perm_value =", value, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueNotEqualTo(String value) {
            addCriterion("perm_value <>", value, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueGreaterThan(String value) {
            addCriterion("perm_value >", value, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueGreaterThanOrEqualTo(String value) {
            addCriterion("perm_value >=", value, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueLessThan(String value) {
            addCriterion("perm_value <", value, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueLessThanOrEqualTo(String value) {
            addCriterion("perm_value <=", value, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueLike(String value) {
            addCriterion("perm_value like", value, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueNotLike(String value) {
            addCriterion("perm_value not like", value, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueIn(List<String> values) {
            addCriterion("perm_value in", values, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueNotIn(List<String> values) {
            addCriterion("perm_value not in", values, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueBetween(String value1, String value2) {
            addCriterion("perm_value between", value1, value2, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermValueNotBetween(String value1, String value2) {
            addCriterion("perm_value not between", value1, value2, "permValue");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentIsNull() {
            addCriterion("perm_attachment is null");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentIsNotNull() {
            addCriterion("perm_attachment is not null");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentEqualTo(String value) {
            addCriterion("perm_attachment =", value, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentNotEqualTo(String value) {
            addCriterion("perm_attachment <>", value, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentGreaterThan(String value) {
            addCriterion("perm_attachment >", value, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentGreaterThanOrEqualTo(String value) {
            addCriterion("perm_attachment >=", value, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentLessThan(String value) {
            addCriterion("perm_attachment <", value, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentLessThanOrEqualTo(String value) {
            addCriterion("perm_attachment <=", value, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentLike(String value) {
            addCriterion("perm_attachment like", value, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentNotLike(String value) {
            addCriterion("perm_attachment not like", value, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentIn(List<String> values) {
            addCriterion("perm_attachment in", values, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentNotIn(List<String> values) {
            addCriterion("perm_attachment not in", values, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentBetween(String value1, String value2) {
            addCriterion("perm_attachment between", value1, value2, "permAttachment");
            return (Criteria) this;
        }

        public Criteria andPermAttachmentNotBetween(String value1, String value2) {
            addCriterion("perm_attachment not between", value1, value2, "permAttachment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boss_permission
     *
     * @mbg.generated do_not_delete_during_merge Mon May 31 16:20:22 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table boss_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}