package me.maiz.project.eduk15boss.model;

import java.io.Serializable;

public class RolePermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_role_permission.role_perm_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer rolePermId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_role_permission.role_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boss_role_permission.perm_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer permId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table boss_role_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_role_permission.role_perm_id
     *
     * @return the value of boss_role_permission.role_perm_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getRolePermId() {
        return rolePermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_role_permission.role_perm_id
     *
     * @param rolePermId the value for boss_role_permission.role_perm_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRolePermId(Integer rolePermId) {
        this.rolePermId = rolePermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_role_permission.role_id
     *
     * @return the value of boss_role_permission.role_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_role_permission.role_id
     *
     * @param roleId the value for boss_role_permission.role_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boss_role_permission.perm_id
     *
     * @return the value of boss_role_permission.perm_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getPermId() {
        return permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boss_role_permission.perm_id
     *
     * @param permId the value for boss_role_permission.perm_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setPermId(Integer permId) {
        this.permId = permId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boss_role_permission
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rolePermId=").append(rolePermId);
        sb.append(", roleId=").append(roleId);
        sb.append(", permId=").append(permId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}