package me.maiz.project.eduk15boss.model;

import java.io.Serializable;
import java.util.Date;

public class Teacher implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_teacher.teacher_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_teacher.user_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_teacher.real_name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_teacher.teacher_desc
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String teacherDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_teacher.raw_add_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Date rawAddTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_teacher.raw_update_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Date rawUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_teacher.teacher_id
     *
     * @return the value of rkt_teacher.teacher_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_teacher.teacher_id
     *
     * @param teacherId the value for rkt_teacher.teacher_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_teacher.user_id
     *
     * @return the value of rkt_teacher.user_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_teacher.user_id
     *
     * @param userId the value for rkt_teacher.user_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_teacher.real_name
     *
     * @return the value of rkt_teacher.real_name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_teacher.real_name
     *
     * @param realName the value for rkt_teacher.real_name
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_teacher.teacher_desc
     *
     * @return the value of rkt_teacher.teacher_desc
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getTeacherDesc() {
        return teacherDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_teacher.teacher_desc
     *
     * @param teacherDesc the value for rkt_teacher.teacher_desc
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setTeacherDesc(String teacherDesc) {
        this.teacherDesc = teacherDesc == null ? null : teacherDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_teacher.raw_add_time
     *
     * @return the value of rkt_teacher.raw_add_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Date getRawAddTime() {
        return rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_teacher.raw_add_time
     *
     * @param rawAddTime the value for rkt_teacher.raw_add_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRawAddTime(Date rawAddTime) {
        this.rawAddTime = rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_teacher.raw_update_time
     *
     * @return the value of rkt_teacher.raw_update_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Date getRawUpdateTime() {
        return rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_teacher.raw_update_time
     *
     * @param rawUpdateTime the value for rkt_teacher.raw_update_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRawUpdateTime(Date rawUpdateTime) {
        this.rawUpdateTime = rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_teacher
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", teacherId=").append(teacherId);
        sb.append(", userId=").append(userId);
        sb.append(", realName=").append(realName);
        sb.append(", teacherDesc=").append(teacherDesc);
        sb.append(", rawAddTime=").append(rawAddTime);
        sb.append(", rawUpdateTime=").append(rawUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}