package me.maiz.project.eduk15boss.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.user_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.username
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.password
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.status
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.email
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.mobile
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.nickname
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.gender
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.avatar
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.last_login_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.last_login_ip
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Integer lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.raw_add_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Date rawAddTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rkt_user.raw_update_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private Date rawUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rkt_user
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.user_id
     *
     * @return the value of rkt_user.user_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.user_id
     *
     * @param userId the value for rkt_user.user_id
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.username
     *
     * @return the value of rkt_user.username
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.username
     *
     * @param username the value for rkt_user.username
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.password
     *
     * @return the value of rkt_user.password
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.password
     *
     * @param password the value for rkt_user.password
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.status
     *
     * @return the value of rkt_user.status
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.status
     *
     * @param status the value for rkt_user.status
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.email
     *
     * @return the value of rkt_user.email
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.email
     *
     * @param email the value for rkt_user.email
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.mobile
     *
     * @return the value of rkt_user.mobile
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.mobile
     *
     * @param mobile the value for rkt_user.mobile
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.nickname
     *
     * @return the value of rkt_user.nickname
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.nickname
     *
     * @param nickname the value for rkt_user.nickname
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.gender
     *
     * @return the value of rkt_user.gender
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.gender
     *
     * @param gender the value for rkt_user.gender
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.avatar
     *
     * @return the value of rkt_user.avatar
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.avatar
     *
     * @param avatar the value for rkt_user.avatar
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.role
     *
     * @return the value of rkt_user.role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.role
     *
     * @param role the value for rkt_user.role
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.last_login_time
     *
     * @return the value of rkt_user.last_login_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.last_login_time
     *
     * @param lastLoginTime the value for rkt_user.last_login_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.last_login_ip
     *
     * @return the value of rkt_user.last_login_ip
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Integer getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.last_login_ip
     *
     * @param lastLoginIp the value for rkt_user.last_login_ip
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setLastLoginIp(Integer lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.raw_add_time
     *
     * @return the value of rkt_user.raw_add_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Date getRawAddTime() {
        return rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.raw_add_time
     *
     * @param rawAddTime the value for rkt_user.raw_add_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRawAddTime(Date rawAddTime) {
        this.rawAddTime = rawAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rkt_user.raw_update_time
     *
     * @return the value of rkt_user.raw_update_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public Date getRawUpdateTime() {
        return rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rkt_user.raw_update_time
     *
     * @param rawUpdateTime the value for rkt_user.raw_update_time
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    public void setRawUpdateTime(Date rawUpdateTime) {
        this.rawUpdateTime = rawUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rkt_user
     *
     * @mbg.generated Mon May 31 16:20:22 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", status=").append(status);
        sb.append(", email=").append(email);
        sb.append(", mobile=").append(mobile);
        sb.append(", nickname=").append(nickname);
        sb.append(", gender=").append(gender);
        sb.append(", avatar=").append(avatar);
        sb.append(", role=").append(role);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", lastLoginIp=").append(lastLoginIp);
        sb.append(", rawAddTime=").append(rawAddTime);
        sb.append(", rawUpdateTime=").append(rawUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}