spring:
  application:
    name: sharding-jdbc-demo
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: me.maiz.shardingjdbcdemo.model
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    org.apache.ibatis: debug