
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/woniu_edu
#    username: root
#    password: root123
#    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.woniuxy.shiro.shiroboot45.model
#  mapper-locations: classpath:mappers/**/*.xml


shiro:
#  未登录时跳转到的登录页面
  loginUrl: /login.html
  unauthorizedUrl: /unauth.html
server:
  port: 8081
