package me.maiz.trainning.framework.ssm.dal.mapper;

import java.util.List;
import me.maiz.trainning.framework.ssm.dal.model.Blog;
import me.maiz.trainning.framework.ssm.dal.model.BlogExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    long countByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int deleteByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int deleteByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    List<Blog> selectByExampleWithRowbounds(BlogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    List<Blog> selectByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    Blog selectByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int updateByExample(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BLOG
     *
     * @mbg.generated Wed Mar 28 15:11:04 CST 2018
     */
    int updateByPrimaryKey(Blog record);
}