spring:
  application:
    name: helloworld
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
logging:
  level:
    org.springframework.ai: debug
    org.springframework.ai.chat.client.advisor: DEBUG
server:
  port: 8777